apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod  # Name of the Pod
  labels:
    name: postgres-pod  # Label to identify the Pod
    app: demo-voting-app  # Label to identify the application
spec:
  containers:
    - name: postgres # Name of the container within the Pod
      image: postgres  # Docker image for the redis
      ports:
        - containerPort: 5432  # Default Port the postgres container listens on
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"