apiVersion: v1
kind: Service
metadata:
  name: db  # Name of the Service
  labels:
    name: postgres-service  # Label to identify the Service
    app: demo-voting-app  # Label to associate the Service with the application
spec:
  ports:
    - port: 5432  # Port on which the Service will be exposed
      targetPort: 5432  # Port that the Service will forward traffic to
  selector:
    name: postgres-pod  
    app: demo-voting-app    # Additional label to match Pods for the application
