apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy # Name of the Deployment
  labels:
    name: redis-deploy  # Label to identify the Deployment
    app: demo-voting-app  # Label to identify the application
spec:
  replicas: 1  # Number of desired replicas of the Pod
  selector: 
    matchLabels:
       name: redis-pod  # Label selector to match Pods managed by this Deployment
       app: demo-voting-app  # Additional label to identify the application
  template:
     metadata:
      name: redis-pod  # Name of the Pod
      labels:
       name: redis-pod  # Label to identify the Pod
       app: demo-voting-app  # Label to identify the application
     spec:
       containers:
         - name: redis # Name of the container within the Pod
           image: redis  # Docker image for the redis
           ports:
            - containerPort: 6379  # Default Port the redis container listens 
