apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod  # Name of the result Pod
  labels:
    name: result-app-pod  # Label to identify the result Pod
    app: demo-voting-app  # Label to identify the application
spec:
  containers:
    - name: result-app-container  # Name of the container within the Pod
      image: kodekloud/examplevotingapp_result:v1  # Docker image for the result app
      ports:
        - containerPort: 80  # Port the container listens on
