apiVersion: v1
kind: Pod
metadata:
  name: worker-pod  # Name of the Pod
  labels:
    name: worker-pod  # Label to identify the Pod
    app: demo-voting-app  # Label to identify the application
spec:
  containers:
    - name: worker-app # Name of the container within the Pod
      image: kodekloud/examplevotingapp_worker:v1  # Docker image for the woker
      